LEXICON_EN: dict[str, str] = {
    "menu_buttons": ("Start Quiz Again", "Help", "Support the Author"),
    "start_quiz": "The quiz begins...",
    "you_right": "✅ Correct! Keep it up.",
    "oh_no": "That's not right. The correct answer is: {correct_answer}",
    "start": "Hello, dear user. I'm Gordon. Would you like to play a game?",
    "restart": "Would you like to play again?",
    "help": "My name is Gordon. I have a habit of writing down all the phrases my friends say.\n"
    "I decided to make a game based on those quotes — it's very simple. Just click the button with the name "
    "of the friend who said the quote.\n"
    "Press the 'Start Quiz Again' button to play my game.",
    "donate": "If you'd like to support the author:\n"
    "Boosty: https://boosty.to/blackcloverquiz \n"
    "It would mean a lot to me ☕",
    "unvalid": "I didn't hear you, say it louder. "
    "(If there are any issues, type /help in the chat)",
    "q1": "❝ To fool your enemies, you must first fool your friends. ❞",
    "q2": "❝ You had no idea, but I’m alive thanks to you. You didn’t even know I existed, but you are all my precious friends. ❞",
    "q3": "❝ Stop blindly trusting everyone. Not all people are kind, not all are great — you’ll regret it one day. ❞",
    "q4": "❝ Even if I can't forgive you, here's what I’ll say to you, Patry: I know you tried. ❞",
    "q5": "❝ Rivals don’t have to be enemies. ❞",
    "q6": "❝ — Ten, nine, eight... \n— What are you counting?\n — Your last moments. ❞",
    "q7": "❝ Brace yourself and be stronger. It’s not shameful to be weak — it’s shameful not to try to surpass yourself. ❞",
    "q8": "❝ — Hey, are you always looking down on me? — I’m not. You're just always hanging around below. ❞",
    "q9": "❝ I’m afraid we can’t understand their reasons... People who hurt others for fun. \n"
    "They do everything for themselves and never feel guilty. \n"
    "Are you curious what they think? I don’t know, and I don’t want to. Pure evil... ❞",
    "q10": "❝ Don’t make anyone worry — that’s what it means to be a man. ❞",
    "characters": {
        "William Vangeance",
        "Yami Sukehiro",
        "Yuno",
        "Nacht Faust",
        "Liebe",
        "Vetto",
        "Luck Voltia",
        "Langris",
        "Magna",
        "Zora Ideale",
        "Gordon",
        "Henry",
        "Damnatio Kira",
        "Valtos",
        "Mimosa",
        "Secre Swallowtail",
        "Asta",
        "Grey",
        "Gauche",
        "Ichika Yami",
        "Nero",
        "Licht",
        "Patry",
        "Mars",
        "William",
        "Nozel",
        "Julius Novachrono",
        "Fuegoleon",
        "Noelle",
        "Zagred",
        "Megicula",
        "Lucifero",
        "Undine",
        "Vanessa",
        "Charmy",
        "Kirsch Vermillion",
        "Solid Silva",
        "Nebra Silva",
        "Morgen Faust",
        "Grill",
        "Lorelai",
    },
    "r1": "Zora Ideale",
    "r2": "Henry",
    "r3": "Zora Ideale",
    "r4": "Licht",
    "r5": "Asta",
    "r6": "Yami Sukehiro",
    "r7": "Fuegoleon",
    "r8": "Noelle",
    "r9": "Nacht Faust",
    "r10": "Magna",
    "final_brilliant": "You’ve shown brilliant knowledge of my friends! 🤩 \n",
    "final_well": "You’ve achieved a great result, worthy of respect! 😉 \n",
    "final_not_bad": "Maybe you're just getting to know my friends! 🤔 \n",
    "final_stmt": "% of your answers were correct!\n",
    "menu_start": "Start Quiz Again",
    "menu_help": "Help",
    "menu_donate": "Support the Author",
    "menu_settings": "Choose Language",
    "menu_choose_action": "Choose an action",
    "throttling": "Wait 10 seconds before sending the next message.",
}
