LEXICON_EN: dict[str, str] = {
    "menu_buttons": ("Start the quiz over", "Help", "Support the author"),
    "start_quiz": "The quiz begins...",
    "you_right": "✅ Correct! Keep it up.",
    "oh_no": "That's incorrect. The correct answer is: {correct_answer}",
    "/start": "Hello, dear user. I'm Gordon. Want to play a game?",
    "/help": "My name is Gordon. I have a habit of writing down all the phrases my friends say.\n"
    + "I decided to try creating a game based on these quotes.\n"
    + "It's very simple: just click the button with the name of the friend who said the quote.\n"
    + "Press the 'Start the quiz again' button to play my game",
    "/donate": "If you want to support the creator of the quiz:\n"
    + "→ Donate on Boosty: https://boosty.to/blackcloverquiz \n"
    + "That would make me very happy ☕",
    "unvalid": "I didn’t hear you, speak up."
    + " (If you're having issues, type /help in chat)",
    "q1": "❝ To fool your enemy, you must first fool your friend. ❞",
    "q2": "❝ You had no idea, but I’m alive thanks to you. You never even knew I existed, but you’re all my precious friends. ❞",
    "q3": "❝ Stop trusting everyone right away. Not all people are kind, not all are great. You might regret it one day. ❞",
    "q4": "❝ Maybe I can’t forgive you, but here’s what I’ll say to you, Patry: I know you tried. ❞",
    "q5": "❝ Rivals don’t have to be enemies. ❞",
    "q6": "❝ — Ten, nine, eight...\n— What are you counting?\n — Your final moments. ❞",
    "q7": "❝ Gather your spirit and become stronger. It’s not shameful to be weak. What’s shameful is not trying to overcome it. ❞",
    "q8": "❝ — Hey, why are you always looking down on me? — I’m not looking down on you. You’re just always hanging around below. ❞",
    "q9": "❝ I’m afraid we can’t understand their reasons... People who hurt others for fun.\n"
    + "They do everything for themselves and never suffer from guilt.\n"
    + "You wonder what such scum think about? I don’t know, and I don’t really care to. Pure evil... ❞",
    "q10": "❝ A real man doesn’t make others worry. ❞",
    "a1": (
        "William Vangeance",
        "Yami Sukehiro",
        "Yuno",
        "Nacht Faust",
        "Liebe",
        "Vetto",
        "Luck Voltia",
        "Langris",
        "Magna",
        "Zora Ideale",
    ),
    "a2": (
        "Gordon",
        "Henry",
        "Damnatio Kira",
        "Augustus Kira Clover XIII",
        "Liebe",
        "Mimosa",
        "Siren Tium",
        "Asta",
        "Nacht Faust",
        "Grey",
    ),
    "a3": (
        "Zora Ideale",
        "Gordon",
        "Grey",
        "Yami Sukehiro",
        "Liebe",
        "Mimosa",
        "Gauche",
        "Ichika Yami",
        "Magna",
        "Nero",
    ),
    "a4": (
        "Licht",
        "Asta",
        "Yuno",
        "Nacht Faust",
        "Patry",
        "Nacht Faust",
        "Yami Sukehiro",
        "Gauche",
        "Nero",
        "Lemiel Silvamillion Clover",
    ),
    "a5": (
        "William",
        "Nozel",
        "Yuno",
        "Yami Sukehiro",
        "Julius Novachrono",
        "Magna",
        "Luck Voltia",
        "Fuegoleon",
        "Noelle",
        "Asta",
    ),
    "a6": (
        "Yami Sukehiro",
        "Nacht Faust",
        "Zagred",
        "Megicula",
        "Lucifero",
        "Ichika Yami",
        "Undine",
        "Magna",
        "Liebe",
        "Vetto",
    ),
    "a7": (
        "Noelle",
        "Damnatio Kira",
        "Yuno",
        "Nacht Faust",
        "Liebe",
        "Fuegoleon",
        "Langris",
        "Grey",
        "Vanessa",
        "Charmy",
    ),
    "a8": (
        "Augustus Kira Clover XIII",
        "Damnatio Kira",
        "Mimosa",
        "Noelle",
        "Liebe",
        "Kirsch Vermillion",
        "Langris",
        "Nacht Faust",
        "Solid Silva",
        "Nebra Silva",
    ),
    "a9": (
        "Nacht Faust",
        "Yami Sukehiro",
        "Yuno",
        "Nacht Faust",
        "Julius Novachrono",
        "Mimosa",
        "Gauche",
        "Morgen Faust",
        "Grill",
        "Vetto",
    ),
    "a10": (
        "Magna",
        "Luck Voltia",
        "Yuno",
        "Nacht Faust",
        "Liebe",
        "Mimosa",
        "Kirsch Vermillion",
        "Ichika Yami",
        "Luck Voltia",
        "Lorelei",
    ),
    "r1": "Zora Ideale",
    "r2": "Henry",
    "r3": "Zora Ideale",
    "r4": "Licht",
    "r5": "Asta",
    "r6": "Yami Sukehiro",
    "r7": "Fuegoleon",
    "r8": "Noelle",
    "r9": "Nacht Faust",
    "r10": "Magna",
    "final_brilliant": "You showed brilliant knowledge of my friends! 🤩 \n",
    "final_well": "You achieved a great result worthy of respect! 😉 \n",
    "final_not_bad": "Maybe you're just getting to know my friends! 🤔 \n",
    "final_stmt": "% of your answers were correct!\n"
    + "I hope you enjoyed my quiz! 🤗",
    "menu_start": "Start quiz again",
    "menu_help": "Help",
    "menu_donate": "Support the author",
    "menu_choose_action": "Choose an action",
}
